description = "Annotimpler JPA"

jar {
    archiveBaseName = "annotimpler.jpa"
}

dependencies {
    api(project(":typeser"))
    api(project(":magicfactory"))
    api(project(":datetime"))
    api(project(":convert"))
    api(project(":core"))
    api(project(":sql"))

    // Jakarta, JPA and friends.
    api("jakarta.annotation:jakarta.annotation-api:"        + versionJakartaAnno)
    api("jakarta.enterprise:jakarta.enterprise.cdi-api:"    + versionJakartaCdi )
    api("jakarta.enterprise:jakarta.enterprise.lang-model:" + versionJakartaCdi )
    api("jakarta.persistence:jakarta.persistence-api:"      + versionJakartaJpa )
    api("jakarta.transaction:jakarta.transaction-api:"      + versionJakartaJta )
    api("jakarta.inject:jakarta.inject-api:"                + versionJakartaInj )
    api("jakarta.interceptor:jakarta.interceptor-api:"      + versionJakartaInt )
    api("jakarta.el:jakarta.el-api:"                        + versionJakartaEl  )

    // Jackson.
    implementation("tools.jackson.core:jackson-core:"     + versionJackson)
    implementation("tools.jackson.core:jackson-databind:" + versionJackson)
    implementation("com.fasterxml.jackson.core:jackson-annotations:" + versionJacksonAnn)

    // H2.
    testImplementation("com.h2database:h2:" + versionH2)

    // SQLite.
    testImplementation("org.xerial:sqlite-jdbc:" + versionSqlite)
}

test {
    jvmArgs += "--enable-native-access=org.xerial.sqlitejdbc"
}
