package ninja.javahacker.sqlplus.stmt;

import edu.umd.cs.findbugs.annotations.Nullable;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLType;
import java.sql.SQLXML;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.List;
import java.util.Map;
import java.util.OptionalDouble;
import java.util.OptionalInt;
import java.util.OptionalLong;
import lombok.NonNull;
import ninja.javahacker.sqlplus.meta.ParsedQuery;

@SuppressWarnings({"PMD.ReplaceJavaUtilCalendar", "PMD.ReplaceJavaUtilDate"})
public interface NamedParameterStatement extends PreparedStatement {

    @NonNull
    public static NamedParameterStatement prepareNamedStatement(
            @NonNull Connection connection,
            @NonNull String query)
            throws SQLException
    {
        return prepareNamedStatement(connection, ParsedQuery.parse(query));
    }

    @NonNull
    @SuppressFBWarnings({"SQL_INJECTION_JDBC", "SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRING"})
    public static NamedParameterStatement prepareNamedStatement(
            @NonNull Connection connection,
            @NonNull ParsedQuery pq)
            throws SQLException
    {
        var ps = connection.prepareStatement(pq.parsed());
        return wrap(ps, pq.params());
    }

    @NonNull
    public static NamedParameterStatement prepareNamedStatement(
            @NonNull Connection connection,
            @NonNull String query,
            int autoGeneratedKeys)
            throws SQLException
    {
        return prepareNamedStatement(connection, ParsedQuery.parse(query), autoGeneratedKeys);
    }

    @NonNull
    @SuppressFBWarnings({"SQL_INJECTION_JDBC", "SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRING"})
    public static NamedParameterStatement prepareNamedStatement(
            @NonNull Connection connection,
            @NonNull ParsedQuery pq,
            int autoGeneratedKeys)
            throws SQLException
    {
        var ps = connection.prepareStatement(pq.parsed(), autoGeneratedKeys);
        return wrap(ps, pq.params());
    }

    @NonNull
    public static NamedParameterStatement wrap(@NonNull PreparedStatement ps, @NonNull Map<String, List<Integer>> params) {
        return new InternalNamedParameterStatement(ps, params);
    }

    @NonNull
    public Map<String, List<Integer>> getIndexes();

    @NonNull
    public default List<Integer> getIndexes(@NonNull String name) {
        var indexes = getIndexes().get(name);
        if (indexes == null) throw new IllegalArgumentException("Parameter not found: " + name);
        return indexes;
    }

    public default void setArray(@NonNull String name, @Nullable java.sql.Array x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setArray(index, x);
        }
    }

    public default void setAsciiStream(@NonNull String name, @Nullable InputStream x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setAsciiStream(index, x);
        }
    }

    public default void setAsciiStream(@NonNull String name, @Nullable InputStream x, int length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setAsciiStream(index, x, length);
        }
    }

    public default void setAsciiStream(@NonNull String name, @Nullable InputStream x, long length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setAsciiStream(index, x, length);
        }
    }

    public default void setBigDecimal(@NonNull String name, @Nullable BigDecimal x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBigDecimal(index, x);
        }
    }

    public default void setBinaryStream(@NonNull String name, @Nullable InputStream x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBinaryStream(index, x);
        }
    }

    public default void setBinaryStream(@NonNull String name, @Nullable InputStream x, int length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBinaryStream(index, x, length);
        }
    }

    public default void setBinaryStream(@NonNull String name, @Nullable InputStream x, long length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBinaryStream(index, x, length);
        }
    }

    public default void setBlob(@NonNull String name, @Nullable Blob x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBlob(index, x);
        }
    }

    public default void setBlob(@NonNull String name, @Nullable InputStream inputStream) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBlob(index, inputStream);
        }
    }

    public default void setBlob(@NonNull String name, @Nullable InputStream inputStream, long length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBlob(index, inputStream, length);
        }
    }

    public default void setBoolean(@NonNull String name, boolean x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBoolean(index, x);
        }
    }

    public default void setByte(@NonNull String name, byte x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setByte(index, x);
        }
    }

    public default void setBytes(@NonNull String name, @Nullable byte[] x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setBytes(index, x);
        }
    }

    public default void setCharacterStream(@NonNull String name, @Nullable Reader reader) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setCharacterStream(index, reader);
        }
    }

    public default void setCharacterStream(@NonNull String name, @Nullable Reader reader, int length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setCharacterStream(index, reader, length);
        }
    }

    public default void setCharacterStream(@NonNull String name, @Nullable Reader reader, long length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setCharacterStream(index, reader, length);
        }
    }

    public default void setClob(@NonNull String name, @Nullable Clob x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setClob(index, x);
        }
    }

    public default void setClob(@NonNull String name, @Nullable Reader reader) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setClob(index, reader);
        }
    }

    public default void setClob(@NonNull String name, @Nullable Reader reader, long length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setClob(index, reader, length);
        }
    }

    public default void setDate(@NonNull String name, @Nullable java.sql.Date x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setDate(index, x);
        }
    }

    public default void setDate(@NonNull String name, @Nullable java.sql.Date x, @Nullable Calendar cal) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setDate(index, x, cal);
        }
    }

    public default void setDouble(@NonNull String name, double x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setDouble(index, x);
        }
    }

    public default void setDouble(int index, @NonNull OptionalDouble x) throws SQLException {
        if (x.isEmpty()) {
            this.setNull(index, Types.DOUBLE);
        } else {
            this.setDouble(index, x.getAsDouble());
        }
    }

    public default void setDouble(@NonNull String name, @NonNull OptionalDouble x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setDouble(index, x);
        }
    }

    public default void setFloat(@NonNull String name, float x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setFloat(index, x);
        }
    }

    public default void setInt(@NonNull String name, int x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setInt(index, x);
        }
    }

    public default void setInt(int index, @NonNull OptionalInt x) throws SQLException {
        if (x.isEmpty()) {
            this.setNull(index, Types.INTEGER);
        } else {
            this.setInt(index, x.getAsInt());
        }
    }

    public default void setInt(@NonNull String name, @NonNull OptionalInt x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setInt(index, x);
        }
    }

    public default void setLocalDate(int index, @Nullable LocalDate x) throws SQLException {
        this.setDate(index, x == null ? null : java.sql.Date.valueOf(x));
    }

    public default void setLocalDate(@NonNull String name, @Nullable LocalDate x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setLocalDate(index, x);
        }
    }

    public default void setLocalDateTime(int index, @Nullable LocalDateTime x) throws SQLException {
        this.setTimestamp(index, x == null ? null : Timestamp.valueOf(x));
    }

    public default void setLocalDateTime(@NonNull String name, @Nullable LocalDateTime x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setLocalDateTime(index, x);
        }
    }

    public default void setLocalTime(int index, @Nullable LocalTime x) throws SQLException {
        this.setTime(index, x == null ? null : java.sql.Time.valueOf(x));
    }

    public default void setLocalTime(@NonNull String name, @Nullable LocalTime x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setLocalTime(index, x);
        }
    }

    public default void setLong(@NonNull String name, long x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setLong(index, x);
        }
    }

    public default void setLong(int index, @NonNull OptionalLong x) throws SQLException {
        if (x.isEmpty()) {
            this.setNull(index, Types.BIGINT);
        } else {
            this.setLong(index, x.getAsLong());
        }
    }

    public default void setLong(@NonNull String name, @NonNull OptionalLong x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setLong(index, x);
        }
    }

    public default void setNCharacterStream(@NonNull String name, @Nullable Reader value) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNCharacterStream(index, value);
        }
    }

    public default void setNCharacterStream(@NonNull String name, @Nullable Reader value, long length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNCharacterStream(index, value, length);
        }
    }

    public default void setNClob(@NonNull String name, @Nullable NClob value) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNClob(index, value);
        }
    }

    public default void setNClob(@NonNull String name, @Nullable Reader reader) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNClob(index, reader);
        }
    }

    public default void setNClob(@NonNull String name, @Nullable Reader reader, long length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNClob(index, reader, length);
        }
    }

    public default void setNString(@NonNull String name, @Nullable String value) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNString(index, value);
        }
    }

    public default void setNull(@NonNull String name, int sqlType) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNull(index, sqlType);
        }
    }

    public default void setNull(@NonNull String name, int sqlType, @Nullable String typeName) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setNull(index, sqlType, typeName);
        }
    }

    public default void setObject(@NonNull String name, @Nullable Object x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setObject(index, x);
        }
    }

    public default void setObject(@NonNull String name, @Nullable Object x, @Nullable SQLType targetType) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setObject(index, x, targetType);
        }
    }

    public default void setObject(@NonNull String name, @Nullable Object x, int targetType) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setObject(index, x, targetType);
        }
    }

    public default void setObject(@NonNull String name, @Nullable Object x, @Nullable SQLType targetType, int scaleOrLength) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setObject(index, x, targetType, scaleOrLength);
        }
    }

    public default void setObject(@NonNull String name, @Nullable Object x, int targetType, int scaleOrLength) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setObject(index, x, targetType, scaleOrLength);
        }
    }

    public default void setRef(@NonNull String name, @Nullable Ref x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setRef(index, x);
        }
    }

    public default void setRowId(@NonNull String name, @Nullable RowId x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setRowId(index, x);
        }
    }

    @SuppressWarnings("checkstyle:AbbreviationAsWordInName")
    public default void setSQLXML(@NonNull String name, @Nullable SQLXML xmlObject) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setSQLXML(index, xmlObject);
        }
    }

    public default void setShort(@NonNull String name, short x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setShort(index, x);
        }
    }

    public default void setString(@NonNull String name, @Nullable String x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setString(index, x);
        }
    }

    public default void setTime(@NonNull String name, @Nullable java.sql.Time x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setTime(index, x);
        }
    }

    public default void setTime(@NonNull String name, @Nullable java.sql.Time x, @Nullable Calendar cal) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setTime(index, x, cal);
        }
    }

    public default void setTimestamp(@NonNull String name, @Nullable Timestamp x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setTimestamp(index, x);
        }
    }

    public default void setTimestamp(@NonNull String name, @Nullable Timestamp x, @Nullable Calendar cal) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setTimestamp(index, x, cal);
        }
    }

    @SuppressWarnings("checkstyle:AbbreviationAsWordInName")
    public default void setURL(@NonNull String name, @Nullable URL x) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setURL(index, x);
        }
    }

    @Deprecated
    public default void setUnicodeStream(@NonNull String name, @Nullable InputStream x, int length) throws SQLException {
        for (var index : getIndexes(name)) {
            this.setUnicodeStream(index, x, length);
        }
    }
}